###
GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:3000/item?name=hello HTTP/1.1

###
POST http://localhost:3000/item HTTP/1.1
content-type: application/json

{
    "name": "hello",
    "colorHex": "#333",
    "price": 123,
    "proveedor": "Alejandro"
}

###
PUT http://localhost:3000/item HTTP/1.1
content-type: application/json

{
    "id": "61a9a6393316c15d7d49c22d",
    "name": "hola"
}

###
DELETE http://localhost:3000/item HTTP/1.1
content-type: application/json

{
    "id": "61a9a6393316c15d7d49c22d"
}

### 
GET http://localhost:3000/menu?name=hello&proveedor=Alejandro HTTP/1.1

###
POST http://localhost:3000/menu HTTP/1.1
content-type: application/json

[
    {
        "name": "hello",
        "colorHex": "#333",
        "price": 123,
        "proveedor": "From MEnu"
    }, {
        "name": "hello",
        "colorHex": "#333",
        "price": 123,
        "proveedor": "from Menu"
    }, {
        "name": "hello",
        "colorHex": "#333",
        "price": 123,
        "proveedor": "from Menu"
    }
]

###
PUT http://localhost:3000/menu HTTP/1.1
content-type: application/json

{
    "id": "61ae60dd22381902f3b98b01",
    "items": [
        {
            "name": "hello",
            "colorHex": "#333",
            "price": 123,
            "proveedor": "AlejandroXD"
        }
    ]
}

###
DELETE http://localhost:3000/menu HTTP/1.1
content-type: application/json

{
    "id": "61ae60dd22381902f3b98b01"
}

### 
GET http://localhost:3000/profile?profileName=hola HTTP/1.1


###
POST http://localhost:3000/profile HTTP/1.1
content-type: application/json

{
    "menuId": "61ae48f27c92fc15adaec41b",
    "profileName": "hola"
}

###
PUT http://localhost:3000/profile?_id=61b274d6a36a1cceb6615a12 HTTP/1.1
content-type: application/json

{
    "profileName": "hola",
    "menuId": "61ae48f27c92fc15adaec41b"
}

###
DELETE http://localhost:3000/profile?_id=61b274d6a36a1cceb6615a12 HTTP/1.1

###
GET http://localhost:3000/user?profileName=HelloWorld HTTP/1.1
###
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "pin": 2345,
    "completeName": "Alejandro Jesús Bautista Arellano",
    "profileName": "HelloWorld"
}
###
POST http://localhost:3000/ HTTP/1.1
content-type: application/json

{}
###
POST http://localhost:3000/ HTTP/1.1
content-type: application/json

{}